baseURL = "http://localhost:8090/"
title = "D'roll Shop"

# Publish Hugo output directly to the PocketBase public directory
publishDir = "../pb_public"

defaultContentLanguage = "ko-kr"
enableLanguages = ["ko-kr", "en"]

[languages]
  [languages.ko-kr]
    languageCode = "ko-kr"
    languageName = "한국어"
    weight = 1
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 2

[params]
heroImg = "https://cdn.midjourney.com/b26ef844-b04c-44e8-9a98-6438d86d3697/0_2.png"
heroTitle = "The Ultimate Driving Machine"
heroSubtitle = "Experience uncompromised performance and luxury with our latest curated collection of premium accessories."

[params.oauth]
google = true
kakao = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "catalog"
url = "/products"
weight = 1

[[menu.main]]
name = "orders"
url = "/my-orders"
weight = 2

[[params.categories]]
name = "퍼포먼스"
nameEn = "Performance"
slug = "performance"
icon = "lightning"

[[params.categories]]
name = "액세서리"
nameEn = "Accessories"
slug = "accessories"
icon = "adjustment"

[[params.categories]]
name = "라이프스타일"
nameEn = "Lifestyle"
slug = "lifestyle"
icon = "card"

[[params.categories]]
name = "신규 상품"
nameEn = "New Arrival"
slug = "new_arrival"
icon = "spark"


[[params.categories]]
name = "할인"
nameEn = "SALE"
slug = "sale"
icon = "lightning"

